### ISSUE TITLE
Screen issue

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#148]
Hello. I encountered this issue :
![1](https://user-images.githubusercontent.com/46350890/75314373-8488ff00-589a-11ea-8b92-5528a4377260.png)

Steps to reproduce:
1. Open dex with dark mode
2. On chart, Click Chart Properties button
3. Enable Light Mode
4. Close Chart Properties table

**Comment by CryptoChaser13** [comment]
I also did reversely:

![1](https://user-images.githubusercontent.com/46350890/75314632-46400f80-589b-11ea-9bef-6df0d2ff7a42.png)

Steps to reproduce:

1. Open dex with light mode
2. On chart, Click Chart Properties button
3. Enable Dark Mode
4. Close Chart Properties table

**Comment by CryptoChaser13** [comment]
Hello sir @thanhson1085 @thanhvk is this reproducible at your side?

**Comment by thanhson1085** [comment]
I can reproduce it. But It is too minor to be considered as an issue. It also a small bug of Tradingview library, not from TomoDEX

**Comment by CryptoChaser13** [comment]
Oh, meaning to say Tradingview is not part of the dex. So many closed issues now i guess sir, it seems you dont accept bugs anymore but rather just receive and compile it, label it closed, but still fix it. Sorry for saying this sir, but its just my sentiment. We are just here to help find any bugs on tomodex.

**Comment by thanhson1085** [comment]
"label it closed, but still fix it", let me know the details, which "closed" issue was fixed? Feel free to drop a comment to the issue to have more discussion.

**Comment by CryptoChaser13** [comment]
Its just my sentiment which is not impossible to happen sir. Anyways, i would want to compare this issue like this was confirmed and i checked was resolved. Please check https://github.com/tomochain/bug-reports/issues/72#issue-553488894 which was confirmed as low bug, and is now fixed. Seems similar, but mysubmitted issue still exists unlike the other one fixed already.

**Comment by thanhson1085** [comment]
See this issue: https://github.com/tomochain/bug-reports/issues/75, we did not accept this bug.
From your view, this bug is same as https://github.com/tomochain/bug-reports/issues/72#issue-553488894
But from developer view, we see the differences:
- It has to open "setting", "switch light mode", "cancel setting" to reproduce the issue. It makes the severity of the issue is to minor to be considered as an issue.
- The chart is using Tranding View iframe, we can not fix this bug if Trading view does not fix it.

**Comment by thanhson1085** [comment]
We also did not accept this bug: https://github.com/tomochain/bug-reports/issues/73

**Comment by CryptoChaser13** [comment]
Okay sir 😇
